all:
  children:
    Core:
      hosts:
        Core-01:
        Core-02:
        Core-03:
        Core-04:
    Access:
      hosts:
        A-PE-01:
        A-PE-02:
        A-PE-03:
        A-PE-04:
        A-PE-05:
        A-PE-06:
    ABR:
      hosts:
        Agg-01:
        Agg-02:
        Agg-03:
        Agg-04:
    PCE:
      hosts:
        SRPCE-01:
        SRPCE-02:
    RR:
      hosts:
        RR-01:

East:
  hosts:
    A-PE-01:
    A-PE-02:
    A-PE-03:
    Agg-01:
    Agg-02:
    SRPCE-01:
West:
  hosts:
    A-PE-04:
    A-PE-05:
    A-PE-06:
    Agg-03:
    Agg-04:
    SRPCE-02:
Core:
  hosts: