---
- name: Getting facts with napalm
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    - name: napalm_get_facts
      napalm_get_facts:
        hostname={{ management_ip }}
        username=napalm
        dev_os={{ os }}
        password=napalm
      #when: commit_changes | match('0')
      when: commit_changes == '0'
      no_log: true

      tags:
        - base