---
- name: Dissable LDP on Routers
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - name: Remove old config
      file: path=$HOME/virl2/UserConfig/{{ inventory_hostname }}/LDP-dissable/ state=absent
      changed_when: False
      no_log: false

    - name: Create empty
      file: path=$HOME/virl2/UserConfig/{{ inventory_hostname }}/LDP-dissable/ state=directory
      changed_when: False

    - name: "Building dissable LDP Configuration"
      template: src=../tasks/roles/LDP-Dissable/templates/{{os}}/DISSABLE-LDP.j2 dest=$HOME/virl2/UserConfig/{{ inventory_hostname }}/LDP-dissable/DISSABLE-LDP.out
      changed_when: False
      tags:
        - sr-mpls
    
    - name: Push configuration with napalm
      napalm_install_config:
          hostname={{ management_ip }}
          username=napalm
          dev_os={{os}}
          password=napalm
          config_file=$HOME/virl2/UserConfig/{{ inventory_hostname }}/LDP-dissable/DISSABLE-LDP.out
          commit_changes={{commit_changes}}
          replace_config=0
          diff_file=$HOME/virl2/UserConfig/{{ inventory_hostname }}/LDP-dissable/diff
      no_log: False