---
- name: Enable Segement Routing
  hosts: all
  connection: local
  gather_facts: no

  tasks:
    
    - name: Remove old config
      file: path=$HOME/virl2/UserConfig/{{ inventory_hostname }}/SR-MPLS/ state=absent
      changed_when: False
      no_log: false

    - name: Create empty
      file: path=$HOME/virl2/UserConfig/{{ inventory_hostname }}/SR-MPLS/ state=directory
      changed_when: False

    - name: "Building SR-MPLS Configuration"
      template: src=../tasks/roles/SR-MPLS/templates/{{os}}/SR-MPLS.j2 dest=$HOME/virl2/UserConfig/{{ inventory_hostname }}/SR-MPLS/SR-MPLS.out
      changed_when: False
      tags:
        - sr-mpls
    
    - name: Push configuration with napalm
      napalm_install_config:
          hostname={{ management_ip }}
          username=napalm
          dev_os={{os}}
          password=napalm
          config_file=$HOME/virl2/UserConfig/{{ inventory_hostname }}/SR-MPLS/SR-MPLS.out
          commit_changes={{commit_changes}}
          replace_config=0
          diff_file=$HOME/virl2/UserConfig/{{ inventory_hostname }}/SR-MPLS/diff
      no_log: False